# This is a basic workflow to help you get started with Actions

name: nested

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the core
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: recursive

          
      - name: copy, commit and push
        working-directory: ./the-sub
        run: |
          pwd
          git remote -v
          date >> readme.md
          git config user.name An-Li-magicloud
          git config user.email lian@magicloud.io
          git add .
          git commit -m "copy"
          git push

        
